### ISSUE TITLE
(Muster-)Brief für das Nachfassen bei ausbleibender oder unvollständiger Antwort

### ISSUE THREAD

**Issue by datenreisen** [DigitaleGesellschaft/Datenauskunftsbegehren#1]
Ein Möglichkeit (oder zumindest Hilfestellung) bieten, um einfach nachfassen zu können, wenn eine Antwort ausbleibt oder unvollständig ist.

**Einstieg auf der Hauptseite:**

![Screenshot at 2023-07-20 13-35-10](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/cd711e16-fe52-4df5-bebd-efda949e74d0)

Über eine zusätzliche Sektion:
```

------------------ oder ---------------------

Ein Brief zum Nachfassen erstellen

* Ich habe keine Antwort erhalten
* Ich habe eine unvollständige Antwort erhalten
* Ich möchte Daten löschen lassen
* Ich möchte Daten korrigieren lassen
```

Dann Eingabe von Datum/Absender/Empfänger:

![Screenshot at 2023-07-20 13-35-41](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/231f249f-c612-4e56-96cc-3c1083f52922)

**Plus Erweiterung der Kalender-Datei:**

![image](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/fd7bc463-cf47-4fac-a20b-4edeb9024c2a)

«Hier kannst Du einen Brief zum Nachfassen erstellen: [LINK]»

Dann Auswahl wie oben («Ein Brief zum Nachfassen erstellen. Ich habe keine Antwort erhalten. Ich habe...»)
Dann Eingabe von Datum/Absender/Empfänger (vorausgefüllt, soweit möglich)

**Plus Erweiterung der Infobox:**

![Screenshot at 2023-07-20 13-52-51](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/f7aa0609-e63a-4ff8-a7ae-52cf3ccbb0ec)

«Und gibt dir die Möglichkeit, einen Brief zum [Nachfassen|Link wie oben] zu erstellen.»

**Comment by giammi64** [comment]
Evtl. kann dieser Text (copy + paste) aus den hinterlegten Links auf der Statseite angezeigt werden.
Falls nötig, könnte der Text auch noch gekürzt werden.


Stellt sich heraus, dass Sie innerhalb von 30 Tagen keine Antwort erhalten haben, so besteht immer noch die Möglichkeit mit einem eingeschriebenen Brief nachzufassen.

Wenn der Inhaber der Datensammlung die Auskunft verweigert, einschränkt oder aufschiebt, muss er Sie darüber informieren, aufgrund welcher gesetzlichen Bestimmung und aufgrund welcher Tatsachen er sich einer vollständigen Auskunftserteilung widersetzt.

Sind Sie der Ansicht, dass der Inhaber der Datensammlung nicht oder nur teilweise seiner Auskunftspflicht nachgekommen ist, können Sie folgendermassen vorgehen:

- Gegen Bundesorgane kann innert 30 Tagen Beschwerde an das Bundesverwaltungsgericht erhoben werden.
- Gegen private Inhaber von Datensammlungen kann am Wohnsitz der betroffenen Person oder am Wohnsitz des Inhabers der Datensammlung eine gerichtliche Klage zur Durchsetzung des Auskunftsrechts eingereicht werden. 
 
Der Richter wird in einem vereinfachten Verfahren entscheiden. Sie können das Gericht direkt anschreiben oder aber einen Rechtsbeistand hinzuziehen.

Fügen Sie Kopien Ihrer Korrespondenz mit dem Inhaber der Datensammlung bei.

https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/ueberblick/das-auskunftsrecht/auskunft-ueber-meine-daten.html#-513897506

https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/ueberblick/das-auskunftsrecht.html

**Comment by datenreisen** [comment]
**Datenauskunftsbegehren**

Sehr geehrte Damen und Herren 

Mit Datum vom TT. MMMM JJJJ habe ich bei Ihnen ein Datenauskunftsbegehren gestellt, das bis jetzt leider unbeantwortet geblieben ist.

Gemäss Art. 1 Abs. 4 der Verordnung zum Bundesgesetz über den Datenschutz (VDSG) muss eine Auskunft oder der begründete Entscheid über die Beschränkung des Auskunftsrechts innert 30 Tagen seit dem Eingang des Auskunftsbegehrens erteilt werden.

Kann die Auskunft nicht innert 30 Tagen erteilt werden, so muss der Inhaber der Datensammlung den Gesuchsteller hierüber benachrichtigen und ihm die Frist mitteilen, in der die Auskunft erfolgen wird.

Darf ich Sie um entsprechende Bearbeitung bitten?

Besten Dank und mit freundlichen Grüssen

Unterschrift
Vorname Name

**Comment by nielsson4711** [comment]
closed with R2023-09.p1
