### ISSUE TITLE
Feature Request: Mehrere Briefe generieren, Adresse behalten

### ISSUE THREAD

**Issue by ganti** [DigitaleGesellschaft/Datenauskunftsbegehren#14]
Wenn man mehrere Briefe generieren will, kommt man vom Brief nur an den Anfang zurück, wenn man die Eingaben zurücksetzt. Es wäre Toll, wenn man wieder auf die Startseite kommen könnte, eine neue Firma auswählen kann und dann auf der zweiten Seite Name und Adresse vom ersten Brief noch da sind

**Comment by benib** [comment]
duplicate of https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/issues/9
