### ISSUE TITLE
Test Environment: Brief drucken erfordert Basic Auth, Abbrechen friert Page ein

### ISSUE THREAD

**Issue by ideadapt** [DigitaleGesellschaft/Datenauskunftsbegehren#15]
Browser: Firefox Developer Edition

Nachdem der Basic Auth Dialog abgebrochen wird, reagiert die Page nicht mehr. Ein Reload ist auch nicht mehr möglich, nur Tab schliessen und wieder öffnen hilft.

Siehe Video.

https://user-images.githubusercontent.com/1071386/119272810-2fa47780-bc08-11eb-8145-6578bb0fd450.mov

**Comment by benib** [comment]
Das betrifft lediglich das test environment da nur da Basic Auth aktiv ist.

**Comment by datenreisen** [comment]
Habe Basic Auth für wwwtest/auskunftsbegehren entfernt, da wir dies nicht mehr brauchen.
