### ISSUE TITLE
Explizite Erwähnung zur kostenlosen Auskunft

### ISSUE THREAD

**Issue by riuriuriu** [DigitaleGesellschaft/Datenauskunftsbegehren#19]
Gratulation zum tollen Online Generator.

Meine Erfahrung ist, dass Mobilfunkprovider als erstes eine Bearbeitungsgebühr von ca 100.- verlangen, bevor relevante Daten heraus gegeben werden. Ich denke, dies schreckt die meisten privaten Auskunftsteller davon ab, nochmals nach zu haken und folglich werden die Daten dann nicht heraus gegeben.

Sollte man im generierten Schreiben nicht explizit erwähnen, dass die Auskunft gemäss DSG Art. 8 Abschnitt 5
**kostenlos** sein muss?

**Comment by datenreisen** [comment]
Merci für die Rückmeldung.

Dies scheint vornehmlich bei UPC der Fall zu sein. Wobei diese Unternehmung auch sonst mit Datenauskunftsbegehren sehr «salopp» umgeht, und auch der Betrag willkürlich gewählt scheint.

Eine Beteiligung an den Kosten kann aber ausnahmsweise tatsächlich [verlangt werden](https://www.fedlex.admin.ch/eli/cc/1993/1962_1962_1962/de#art_2) (max. 300 Franken), wobei eine solche bei Daten aus der Vorratsdatenspeicherung m.E. nicht gerechtfertigt ist (und eine Auskunft zurückgezogen werden müsste!). Ein klärendes Urteil wäre spannend.

Einen Hinweis gibt es bei den Erklärungen (oben rechts im Generator).
