### ISSUE TITLE
(Muster-)Brief für Korrektur oder Löschen von Daten

### ISSUE THREAD

**Issue by datenreisen** [DigitaleGesellschaft/Datenauskunftsbegehren#2]
Ein Möglichkeit (oder zumindest Hilfestellung) bieten, um einfach eine Korrektur oder das Löschen von Daten verlangen zu können.

**Comment by datenreisen** [comment]
Ein Möglichkeit (oder zumindest Hilfestellung) bieten, um einfach nachfassen zu können, wenn eine Antwort ausbleibt oder unvollständig ist.

Einstieg auf der Hauptseite:

![Screenshot at 2023-07-20 13-35-10](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/cd711e16-fe52-4df5-bebd-efda949e74d0)

Über eine zusätzliche Sektion:
```

------------------ oder ---------------------

Ein Brief zum Nachfassen erstellen

* Ich habe keine Antwort erhalten
* Ich habe eine unvollständige Antwort erhalten
* Ich möchte Daten löschen lassen
* Ich möchte Daten korrigieren lassen
```

Dann Eingabe von Datum/Absender/Empfänger:

![Screenshot at 2023-07-20 13-35-41](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/231f249f-c612-4e56-96cc-3c1083f52922)

**Comment by datenreisen** [comment]
Plus Erweiterung der Kalender-Datei:

![image](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/fd7bc463-cf47-4fac-a20b-4edeb9024c2a)


«Hier kannst Du einen Brief zum Nachfassen erstellen: [LINK]»

Dann Auswahl wie oben («Ein Brief zum Nachfassen erstellen. Ich habe keine Antwort erhalten. Ich habe...»)
Dann Eingabe von Datum/Absender/Empfänger (vorausgefüllt, soweit möglich)

**Comment by datenreisen** [comment]
Plus Erweiterung der Infobox:

![Screenshot at 2023-07-20 13-52-51](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/f7aa0609-e63a-4ff8-a7ae-52cf3ccbb0ec)


«Und gibt dir die Möglichkeit, einen Brief zum [Nachfassen|Link wie oben] zu erstellen.»

**Comment by nielsson4711** [comment]
closed with R2023-09 p1
