### ISSUE TITLE
E-Mail Kontaktdaten verlangen, wo nicht ohnehin nötig.

### ISSUE THREAD

**Issue by Tomagori** [DigitaleGesellschaft/Datenauskunftsbegehren#20]
Der bisherige Standardbrief erwähnt, dass man die Daten gerne in digitalem Format, etwa auf einem USB Stick erhalten will. Da es nicht sehr gute Praxis ist, zugeschickte UBS-Sticks in den eigenen PC zu stecken, sollte der User bei allen Briefen, die nicht bereits aufgrund der Natur des Auskunftsbegehrens die E-Mail enthalten, die Möglichkeit haben, diese im Formular anzugeben. Die Mail sollte dann (egal ob im Rahmen des Auskunftsnegehrens oder wie beschrieben separat) in den Satz betr. Form der Auskunft integriert werden, womöglich sogar auf Kosten der USB-Variante, die mir sicherheitstechnisch wirklich eher suboptimal erscheint.

**Comment by datenreisen** [comment]
Der Satz bezüglich der Form der beauskunfteten Daten lässt sich gut den eigenen Vorstellungen anpassen (= ist editierbar). 

Leider haben alle Möglichkeiten, wie CD, USB-Stick, E-Mail, verschlüsselt per E-Mail gewichtige Nachteile (Verbreitung, Datensicherheit, Datenschutz, Handhabung...). Den USB-Stick haben wir (z.Z.) als die am wenigsten schlechte Variante angesehen. Dein Unbehagen ist aber komplett berechtigt.
