### ISSUE TITLE
Position Adresszeilen

### ISSUE THREAD

**Issue by giammi64** [DigitaleGesellschaft/Datenauskunftsbegehren#22]
Wir haben den Input erhalten, dass unsere Adresszeiel nicht optimal positioniert ist. Habe es auch selbst getestet und manchmal muss man den Brief neu positionieren, da das Couvert die Adresszeile verdecken kann.
Ich habe die Position via Latex-Klasse "chletter" geprüft, die sich an die Schweizer Norm SN 010130 hält.
Demzufolge müsste die Position der Adresszeile um 0.8 cm nach rechts verstellt werden. Siehe Bild.
![Scanned Document](https://user-images.githubusercontent.com/73934892/159504225-69960479-4694-49eb-8dde-f4bc109c569c.jpg)

**Comment by nielsson4711** [comment]
Zugriff auf einen Auszug der SN 010130 mit den relevanten Abmessungen wäre für den Fix hilfreich. Womöglich hat es ja bereits eine Lizenz im Zugriff.

**Comment by nielsson4711** [comment]
closed with R2023-09.p1
