### ISSUE TITLE
Kompatibilität zum revDSG

### ISSUE THREAD

**Issue by datenreisen** [DigitaleGesellschaft/Datenauskunftsbegehren#23]
Am 1. September tritt das revDSG in Kraft. Der Brief benötigt daher einige Anpassungen.

**Comment by nielsson4711** [comment]
Texte und Textbausteine revidieren.

**Comment by nielsson4711** [comment]
solved.

**Comment by nielsson4711** [comment]
closed with R2023-09.p1
