### ISSUE TITLE
Zeilenumbruch in Kalender-Datei

### ISSUE THREAD

**Issue by datenreisen** [DigitaleGesellschaft/Datenauskunftsbegehren#24]
Die Kalenderdatei wird mit Zeilenumbrüchen nach 75 Zeichen generiert. Dies sieht etwas unschön aus. Ist dies zwingend so. Und falls ja, könnten wir den Umbruch manuell (z.B.  nach jedem Satz/Punkt) gestalten?

![Screenshot at 2023-07-20 13-16-34](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/assets/4204720/adee675b-c5ff-4bf9-95ea-28e897b50be6)

**Comment by datenreisen** [comment]
Plus Ergänzung: Bei Fragen kannst Du uns gern über auskunftsbegehren@digitale-gesellschaft.ch kontaktieren.

**Comment by nielsson4711** [comment]
closed with R2023-09.p1
