### ISSUE TITLE
Generator für Herausgabebegehren 

### ISSUE THREAD

**Issue by homo-iocus** [DigitaleGesellschaft/Datenauskunftsbegehren#40]
Vorab, vielen Dank für die Entwicklung des Brief-Generators!

Es wäre nützlich falls man neben dem Auskunftsbegehren auch einen Generator für die Durchsetzung des Rechts auf Datenherausgabe (nach Art. 28 des DSG) zur Hand hätte.

**Comment by datenreisen** [comment]
Interessant! Vielen Dank. Ich habe den Vorschlag in die List der anderen Erweiterungen aufgenommen (#4)

**Comment by nielsson4711** [comment]
> Vorab, vielen Dank für die Entwicklung des Brief-Generators!
> 
> Es wäre nützlich falls man neben dem Auskunftsbegehren auch einen Generator für die Durchsetzung des Rechts auf Datenherausgabe (nach Art. 28 des DSG) zur Hand hätte.

Der Vorschlag ist nun umgesetzt in branch "_add_desire_handover_". Zur Anwendung muss jeweils auch die ergänzte Datenstruktur aus dem gleichnamigen Branch im Projekt [Datenauskunftsbegehren-Data](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data) das Verzeichnis "_public_" übernommen werden. Die Anpassung ist dort mit der Datei _src/desire/data_handover.yml_ umgesetzt. Es braucht einen _build_ der Datendatei "_data.js_"!

https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/tree/add_desire_handover
https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/tree/add_desire_handover
