### ISSUE TITLE
"Zusätliches Auskunftsbegehren" (und eigene Eingaben behalten)

### ISSUE THREAD

**Issue by benib** [DigitaleGesellschaft/Datenauskunftsbegehren#9]
Zum Beispiel hier wäre es super, ich könnte gleich ein neues Auskunftsbegehren mit meinen Eingaben machen um nicht immer wieder meine Adresse eingeben zu müssen.

<img width="789" alt="Screenshot 2021-05-18 at 10 25 53" src="https://user-images.githubusercontent.com/821875/118617998-77b83a00-b7c3-11eb-95a2-8c2969896a88.png">

**Comment by Tomagori** [comment]
Fände das auch super. Wäre mE bereits ganz am Anfang ideal, damit man beim "Direkt ein Unternehmen oder eine Behörde auswählen" einfach mehrere im dropdown selektieren könnte, und dann ein ganzer batch sofort generiert wird.

**Comment by nielsson4711** [comment]
Das Beibehalten eingegebener Daten ist bereits möglich. Dies gilt für Absender, Empfänger, Datum und auch den Brieftyp. 

Eine Mehrfachverarbeitung (batch) ist nicht enthalten, kann aber einfach von aussen gesteuert werden. Hinweis: Die Druckaufbereitung aus dem Programmcode erfolgt nicht selbständig. Sie erfordert die Unterstützung durch Mittel von Browser und Betriebssystem.

## Grobe, schrittweise Anleitung zur Serienverarbeitung:

### 1. Organisationen identifizieren
Eine Liste der anzuschreibenden Organisationen mit dem Datenattribut "**name**" erstellen.

Das Attribut ist hier erläutert: `https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/blob/main/data/orgs/_template.yml`

Beispiel:

- atupri
- CH Media

### 2. Anschreiben (Datenauskunftsbegehren) erstellen
In der Ansicht "_Brief erstellen_" mit dem vollständigen Brieftext die URL aus der Adresszeile des Browsers kopieren.

### 3. Für das nächste Anschreiben den Namen in der URL austauschen:

Beispiel: 
`https://wwwtest.digitale-gesellschaft.ch/auskunftsbegehren/#%7B%22v%22:1,%22entry%22:%22type%22,%22types%22:%5B%22mobility%22%5D,%22name%22:%22Tim%20Tom%22,%22address%22:%22Bergweg%2022%5Cn9999%20Talsiten%22,%22org%22:%22Mobility%22,%22step%22:%22data_info_request%22,%22date%22:%2229.8.2023%22%7D  
`
Organisationseintrag = %22org%22:%22Mobility%22
Nächster Organisationseintrag = %22org%22:%CH Media%22

### 4. Geänderte URL aufrufen
   Voilá

### 5. Anschreiben zum "Nachfassen" in Serie
   Dazu die Attribute "entry" und "step" der URL austauschen:
   
   entry = `followup` (da es um das Nachfassen geht)
   step = Verb füllen mit einem aus `https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/tree/main/data/desires`
   
   Beispiel:
     Anschreiben: entry = "type", step = "data_info_request"
     Nachfassen "unvollständige Antwort": entry = "followup", step = "incomplete_answer"

   **HINWEIS**: Das _Referenzdatum im Brief zum Nachfassen_ wird heute NICHT automatisch gefüllt. Denn der Programmcode kann nicht "wissen", ob und wann eine Antwort einging.
   
### 6. geänderte URL aufrufen
   Voilá
